### ISSUE TITLE
How to pretty-print everything?   

### ISSUE THREAD

**Issue by pcj** [bazelbuild/buildifier#11]
Is is possible to pretty-print more aggressively, including python (skylark) blocks? It only seems to cleans up whitelisted content (in tables.go I guess).  It does not seem catch syntax errors either. For example:

```go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	bzl "github.com/bazelbuild/buildifier/core"
)

func main() {
        var buf = bytes.Buffer
        out := bufio.NewWriter(&buf)
        bzlIn := "def foo():\n   pass\n"
        nBytes, err := out.WriteString(bzlIn)
        build, err := bzl.Parse("BUILD", out.Bytes())
        bzlOut, err := bzl.Format(build)
}
```

Is there a recommended approach to pretty-print arbitrary skylark code?

**Comment by pmbethe09** [comment]
Can you give the example skylark code that is not cleaned up?

FYI if there are syntax errors, then nothing happens (which is one way to
know there are such errros).

**Comment by pcj** [comment]
I can substitute any garbage in the bzlIn string above, and the corresponding output is passed directly through (agrees with your previous comment).  

Is there a way to trigger an error on bad input?

**Comment by pmbethe09** [comment]
Can you give an example BUILD file or .bzl which is not printed correctly?  In the default mode buildifier should either fix everything, or exit 1 if syntax is wrong

**Comment by laurentlb** [comment]
Buildifier was designed for BUILD files, not bzl files. In a .bzl file, it will skip any function definition, for example.

We'll provide tooling for bzl files in the future.

**Comment by pcj** [comment]
Ok, thanks for the clarification about bzl files.

**Comment by dpursehouse** [comment]
> We'll provide tooling for bzl files in the future.

@laurentlb has this been done yet?

**Comment by laurentlb** [comment]
Not yet. I agree it will be very useful, and many people have been asking for it.
It will take some time, but it's definitely on our goals for this year.

**Comment by junghoahnsc** [comment]
Is there any tool to use for bzl (Skylark) files until builldifier supports it?

**Comment by laurentlb** [comment]
You can try pyformat (https://pypi.python.org/pypi/pyformat).

**Comment by dpursehouse** [comment]
I tried pyformat and found that unfortunately it doesn't format consistently with buildifier.

For example:

- It replaces double quotes (`"`) with single quotes (`'`) which is the opposite to buildifier.
- It wraps lines at fewer columns than buildifier

these are not huge differences, but for projects that have many `.bzl` files (Gerrit has 20+)  this could cause unnecessary churn when/if we would later reformat again with buildifier.

**Comment by junghoahnsc** [comment]
I also tried yapf, but it's a bit different from buildifier.
