### ISSUE TITLE
Check in generated code

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/buildifier#14]
Can you please check in genearted code?

From https://blog.golang.org/generate:

> if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients

Having to generate code does not work well with common dependency management tools in the go ecosystem such as godeps and glide.

**Comment by pmbethe09** [comment]
That is a hard sell for me, coming from bazel-land where you shouldn't
check any generated files in, to avoid staleness caused by forgetting to
re-generate.

**Comment by mikedanese** [comment]
It seems to be not the go way but It's easy enough to workaround.

**Comment by pmbethe09** [comment]
If it means a lot to you, I would be OK with it, but you should add a
sh_test to the BUILD file that checks that the generated code is identical
to the one that is checked in, to avoid staleness.

**Comment by mattmoor** [comment]
Gazelle doesn't like this and wants to rewrite it in a way that breaks the build.

See [here](https://github.com/kubernetes/test-infra/pull/4859#issuecomment-347749178).

I'm going to attempt a PR to fix this.
