### ISSUE TITLE
core build is broken

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/buildifier#16]
When installing the gazelle command, these errors occur:

    $  go get -u github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
    # github.com/bazelbuild/buildifier/core
    ../../bazelbuild/buildifier/core/lex.go:142: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:155: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:170: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:433: undefined: _AND
    ../../bazelbuild/buildifier/core/lex.go:434: undefined: _FOR
    ../../bazelbuild/buildifier/core/lex.go:435: undefined: _IF
    ../../bazelbuild/buildifier/core/lex.go:436: undefined: _ELSE
    ../../bazelbuild/buildifier/core/lex.go:437: undefined: _IN
    ../../bazelbuild/buildifier/core/lex.go:438: undefined: _IS
    ../../bazelbuild/buildifier/core/lex.go:439: undefined: _LAMBDA
    ../../bazelbuild/buildifier/core/lex.go:439: too many errors

I imagine a generated file didn't get checked into the repo.

**Comment by jmhodges** [comment]
(Similarly, the instructions to use `go install` in the README will also lead to this problem.)

**Comment by pmbethe09** [comment]
As mentioned in the other thread, for bazel-style reasons, not checking in was intentional.
As to the README, it indicates that you should run:
go get -d -u github.com/bazelbuild/buildifier/buildifier && go generate github.com/bazelbuild/buildifier/core && go install github.com/bazelbuild/buildifier/buildifier

**Comment by jmhodges** [comment]
So, I was going to tools on top of it (like a godeps file to bazel converter) but this means I'm going to have to either fork gazelle/generator and buildifier/core so that other folks can `go get` it, or make everyone have to run these commands all over.

It seems like a waste to go against the community standard for a really handy project is all.

**Comment by jmhodges** [comment]
(Currently, gazelle doesn't generate the repositories needed to download Go packages, so I was going to try and create them myself.)

**Comment by pmbethe09** [comment]
As I wrote in https://github.com/bazelbuild/buildifier/issues/14
I could be convinced to accept this change if a test is added to BUILD to ensure the files are in sync.
