### ISSUE TITLE
Set //buildifier:buildifier to visibility:public for bazel

### ISSUE THREAD

**Issue by jwnimmer-tri** [bazelbuild/buildifier#21]
In `buildifier/BUILD`, could we set `visibility = ["//visibility:public"]` on the `go_binary(name = "buildifier", ...)` rule?

I would like to bring the `buildifier` project into my `WORKSPACE` and refer to that binary as a dependency, but the target defaults to private (at least when using `bazel`).

**Comment by pmbethe09** [comment]
Sure, send a PR
