### ISSUE TITLE
Buildifier undoes raw strings

### ISSUE THREAD

**Issue by jwnimmer-tri** [bazelbuild/buildifier#33]
Buildifier turns raw string literals into regular strings, which makes inline shell code and regexps more difficult to read.   See for example RobotLocomotion/drake@a4a313ee0ef0a8e4654cfa52ad8b72a34e214bc7.

**Comment by pmbethe09** [comment]
The google-internal response is "working as intended".

**Comment by laurentlb** [comment]
More specifically, "Uniformity trumps choice here."
