### ISSUE TITLE
Recent commits broke the CI tests

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/buildifier#59]
All builds here are yellow now: http://ci.bazel.io/job/buildifier/, test targets `//api_proto:api.gen.pb.go_checkshtest` and `//build_proto:build.gen.pb.go_checkshtest` are now broken.

**Comment by pmbethe09** [comment]
Hmm, I think I never integrated the build-status labels the way they work for rules_go

**Comment by pmbethe09** [comment]
Fix PR:
https://github.com/bazelbuild/buildifier/pull/60

**Comment by vladmos** [comment]
Thanks, it's fixed now.
