### ISSUE TITLE
Buildozer can't print attrs whose values are more complicated expressions

### ISSUE THREAD

**Issue by swolchok** [bazelbuild/buildifier#61]
If I have a rule like
```
test_suite(
    name = "example",
    some_attr = ["foo"] + SOME_CONSTANT,
)
```

and I run `buildozer //:example "print some_attr"`, it prints `(unknown)`. It seems straightforward to instead print `["foo"] + SOME_CONSTANT` using `build.FormatString`. Is there any reason buildozer shouldn't do this?

**Comment by pmbethe09** [comment]
probably this code isn't smart enough:
https://github.com/bazelbuild/buildifier/blob/master/edit/buildozer.go#L323
